#!/bin/bash
 ls -a "$1" | grep ".env.*" >> envfile.txt
mkdir logs/
while read "$i"; do
   while read j; do
       
done < envfile.txt


#so logic is put in a loop and take directory one by one , then list all .env.* type files into envfile.txt then put while loop and 
# read each env file name then a while loop to read contents line by line then check lines using rejex, sed etc . then put accordingly to 
# log file and display

piping |
>, >> redirection
